### PR TITLE
BL-886-all-create-an-implementation-plan

### PR DESCRIPTION
**Pull request by randynobx**
## Description

Creates the framework for a detailed step-by-step guide for deployment of the Underdog Devs Resource Management Platform.

All guide documents live under the `Deployment-Guide` directory and are labeled in the order that they should be followed. There is also a directory `README.md` that provides an overview of the process and links to other relevant documents.

The DS, BE, and FE teams may now assume maintenance of their specific deployment guides.

#### Video Link
[Loom video](https://www.loom.com/share/5922b6c60312456b8e6518efdb7745b1)

#### Jira Link

[BL-886](https://bloomtechlabs.atlassian.net/browse/BL-886)

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by zoebrantley — APPROVED** [review]
These guides are formatted wonderfully. Really excited to see how these fill up as time goes on, and should be a major help to new learners coming into Labs.

**Review by TophertheCoder — APPROVED** [review]
This is a fantastic layout and start to what will be a very helpful tool not just for underdog devs but for future projects! Clear, concise, readable, and clean. Great work

**Comment by ezra-casas** [comment]
Great work.
I don’t have any further comments.

**Review by bkautz0824 — APPROVED** [review]
This will be really helpful.  I love the layout of a general readme that walks us through where to find things in the repo. The contents section that links to other parts of the repo is a great idea too.  Having consistent documentation like this will help new learners onboard as well.

**Review by JeffDesch — APPROVED** [review]
Excellently organized skeleton framework for the deployment docs, this will likely save future doc writers considerable confusion.

**Review by tim-sansone — APPROVED** [review]
Overall great work creating this implementation plan. The structure you've laid out here is very straightforward and should be easy for our client to follow. Keeping things simple and step-by-step is the way to go.

We definitely need to go over each README very carefully to make sure they are updated. The BE README especially needs a lot of updating to reflect the changes from the switch to Mongo.

**Pull request merged**
