### PR TITLE
Added screenshot of analytics page design

### PR DESCRIPTION
**Pull request by andrewgomez1992**
## Description

Added screenshot of analytics page design

https://bloomtechlabs.atlassian.net/browse/BL-913?atlOrigin=eyJpIjoiMjc3ZjQ5MTQzNGNhNDFlNjkyZjBjNDEwYmM0NzBjNWMiLCJwIjoiaiJ9

#### Video Link

[Loom Video](https://www.loom.com/share/dc1695ccb8cf448f942b3aba732b987c)

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by Mitchathy — COMMENTED** [review]
*

**Review by Mitchathy — APPROVED** [review]
The design looks very clean! Thank you for adding it to the docs

**Review by bkautz0824 — APPROVED** [review]
This is a great way to display both the mentees and mentors at the same time.  My only concern would be if there is ever the same amount of mentees and mentors.  Outside of that concern, the design is clean and descriptive.

**Comment by JTCoates45** [comment]
Nice design looks clean and gets your point across clear and concise.

**Review by tim-sansone — APPROVED** [review]
Overall this looks good and I believe it conveys the desired information. A couple of notes:

At a glance the term "count of records" was confusing to me. Will an average admin know what that means? Maybe something like "number of users" would better describe that axis?

Also, are these graphs overlaid or stacked? In other words, are there 2 Android mentors and 3 Android mentees or are there 2 Android mentors and 5 Android mentess? I might be the only one confused by that. If so, feel free to disregard.

**Comment by BrokenShell** [comment]
> Overall this looks good and I believe it conveys the desired information. A couple of notes:
> 
> At a glance the term "count of records" was confusing to me. Will an average admin know what that means? Maybe something like "number of users" would better describe that axis?
> 
> Also, are these graphs overlaid or stacked? In other words, are there 2 Android mentors and 3 Android mentees or are there 2 Android mentors and 5 Android mentess? I might be the only one confused by that. If so, feel free to disregard.

Good question! They are stacked. In production an admin will be able to hover over a particular bar to see additional info including the total count.

**Pull request merged**
