### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by TophertheCoder**
## Description

created a whimsical flow chart to show the process of data from front end to back end and data science.

#### Video Link

[Loom Video](https://www.loom.com/share/a03d7aa8705246fd9b9fbdd14824d3f6)

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by matt-arofin — CHANGES_REQUESTED** [review]
A visually descriptive flowchart - I can clearly see the relationships between the various layers of the app. Great job! My only suggestion would be a more descriptive file name for clearer context.

**Review by MaxT6 — APPROVED** [review]
Excellent visual! This makes understanding the flow of data very easy to understand. Thank you for creating this!

**Review by matt-arofin — APPROVED** [review]

**Review by Nicholas-R-Payne — APPROVED** [review]
Flowchart looks good, great work!

**Review by ezra-casas — APPROVED** [review]
Love the simplicity! Awesome work 👍

**Review by paulMorrow1 — APPROVED** [review]
Nice Flow chart, makes it easy to understand the user interaction.

**Review by woodbenwood — APPROVED** [review]
This is fantastic, and so clear, it almost doesn't need the Loom video. But I watched that too, and it's equally fantastic. Thanks for taking the time to bring clarity to the chaos. Too little of that in this cold, barren multiverse. Entropy may eventually win, but it's the struggle against that brings us mortals meaning.

**Review by woodbenwood — APPROVED** [review]

**Review by JeffDesch — APPROVED** [review]
Visually appealing while also very legible re: typeset choice and use of distinguishing shapes. Great job!

**Pull request merged**
